name: CI/CD Pipeline

on:
 push:
  branches:
	- main
  pull_requests:
   branches:
	- main


jobs:
 build:
  runs-on: ubuntu-latest

  steps:
	- name: Checkout Code
	- uses: actions/checkout@v2

	- name: Set up Python
	- uses: actions/setup-python@v2
	  with:
	   python-version: '3.x'

	- name: Install Dependencies
	  run: | python -m pip install --upgrade pip
		 pip install -r requirements.txt

	- name: Build Docker Image
	  run: | docker build -t flask-app .

	- name: Run Docker Container
	  run: | docker run -d -p 5000:5000 flask-app


